Trax/Trax/Areas/Admin/Controllers/ServiceCategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Trax.Services.Repository.IRepository;

namespace Trax.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles="Admin,Moderator")]
    public class ServiceCategoryController : Controller
    {
        private readonly IServiceCategory _serviceCategory;

        public ServiceCategoryController(IServiceCategory serviceCategory)
        {
            _serviceCategory = serviceCategory;
        }
        public IActionResult Index(int page = 1)
        {
            ViewBag.Active = "Social";
            List<Models.ServiceCategory> serviceCategory1 = _serviceCategory.GetServiceCategory();
            decimal dataPage = 3;
            decimal pageCount = Math.Ceiling(serviceCategory1.Count / dataPage);

            List<Models.ServiceCategory> serviceCategory2 = serviceCategory1.OrderByDescending(o => o.Id).Skip(Convert.ToInt32((page - 1) * dataPage)).Take((int)dataPage).ToList();
            ViewBag.CurrentPage = page;
            ViewBag.PageCount = pageCount;
            ViewBag.DataPage = dataPage;
            ViewBag.DataCount = serviceCategory1.Count;
            return View(serviceCategory2);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Models.ServiceCategory model)
        {
            if (ModelState.IsValid)
            {
                _serviceCategory.CreateServiceCategory(model);

                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult Update(int serviceCategoryId)
        {
            if (serviceCategoryId <= 0)
            {
                return NotFound();
            }
            Models.ServiceCategory serviceCategory = _serviceCategory.GetServiceCategory(serviceCategoryId);
            return View(serviceCategory);
        }

        [HttpPost]
        public IActionResult Update(Models.ServiceCategory model)
        {
            if (ModelState.IsValid)
            {
                _serviceCategory.UpdateServiceCategory(model);

                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Duzgun duzelt!");
            return View();

        }
        public IActionResult Delete(int servicecategoryId)
        {
            _serviceCategory.DeleteServiceCategory(servicecategoryId);

            return RedirectToAction("Index");
        }


    }
}

Trax/Trax/Areas/Admin/Views/ServiceCategory/Create.cshtml
@model ServiceCategory
@{
    ViewData["Title"] = "Create";
}

<div class="intro-y flex items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Create Position
    </h2>
</div>
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 lg:col-span-6">
        <!-- BEGIN: Form Layout -->
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" style="color:red; margin-bottom:30px;"></div>
            <div class="intro-y box p-5">
                <div>
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="input w-full border mt-2">
                </div>

                <div class="text-right mt-5">
                    <a asp-area="admin" asp-controller="ServiceCategory" asp-action="index" class="button w-24 border text-gray-700 mr-1">Cancel</a>
                    <button type="submit" class="button w-24 bg-theme-1 text-white">Create</button>
                </div>
            </div>
        </form>
        <!-- END: Form Layout -->
    </div>
</div>

Trax/Trax/Areas/Admin/Views/ServiceCategory/Index.cshtml
@model List<ServiceCategory>
@{
    ViewData["Title"] = "Index";
    int firstRow = (int)((ViewBag.CurrentPage - 1) * ViewBag.DataPage);
}

<h2 class="intro-y text-lg font-medium mt-10">
    ServiceCategory
</h2>
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-no-wrap items-center mt-2">
        <a class="button text-white bg-theme-1 shadow-md mr-2" asp-area="Admin" asp-controller="ServiceCategory" asp-action="Create">Add ServiceCategory</a>

        <div class="hidden md:block mx-auto text-gray-600">Showing @(firstRow + 1) to @(firstRow + ViewBag.DataPage ) of @ViewBag.DataCount entries</div>

    </div>
    <!-- BEGIN: Data List -->
    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <table class="table table-report -mt-2">
            <thead>
                <tr>
                    <th class="whitespace-no-wrap">#</th>
                    <th class="text-center whitespace-no-wrap">Name</th>


                    <th class="text-center whitespace-no-wrap">Action</th>
                </tr>
            </thead>
            <tbody>
                @{ int i = firstRow;}
                @foreach (var item in Model)
                {
                    i++;
                    <tr class="intro-x">
                        <td class="w-40">
                            @i
                        </td>
                        <td class="text-center">@item.Name</td>




                        <td class="w-40">
                            <div class="flex items-center justify-center text-theme-9"> <i data-feather="check-square" class="w-4 h-4 mr-2"></i> Active </div>
                        </td>
                        <td class="table-report__action w-56">
                            <div class="flex justify-center items-center">
                                <a class="flex items-center mr-3" asp-area="admin" asp-controller="ServiceCategory" asp-action="update" asp-route-servicecategoryId="@item.Id"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Edit </a>
                                <a class="flex items-center text-theme-6" asp-area="admin" asp-controller="ServiceCategory" asp-action="delete" asp-route-servicecategoryId="@item.Id" onclick="return confirm('Are you sure?')"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- END: Data List -->
    <!-- BEGIN: Pagination -->
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-row sm:flex-no-wrap items-center">
        <ul class="pagination">
            <li>
                <a class="pagination__link" asp-area="Admin" asp-controller="ServiceCategory" asp-action="index" asp-route-page="1"> <i class="w-4 h-4" data-feather="chevrons-left"></i> </a>
            </li>
            <li>
                <a class="pagination__link" asp-area="Admin" asp-controller="ServiceCategory" asp-action="index" asp-route-page="@(ViewBag.CurrentPage<=1?1: ViewBag.CurrentPage - 1)"> <i class="w-4 h-4" data-feather="chevron-left"></i> </a>
            </li>
            <li> <a class="pagination__link" href="~/Areas/Admin/">...</a> </li>
            @for (int j = 1; j <= ViewBag.PageCount; j++)
            {
                <li> <a class="pagination__link @(j==ViewBag.CurrentPage ?"pagination__link--active":"")" asp-area="admin" asp-controller="ServiceCategory" asp-action="index" asp-route-page="@j">@j</a> </li>
            }
            <li> <a class="pagination__link" href="~/Areas/Admin/">...</a> </li>
            <li>
                <a class="pagination__link" asp-area="admin" asp-controller="ServiceCategory" asp-action="index" asp-route-page="@(ViewBag.CurrentPage>=ViewBag.PageCount?ViewBag.PageCount:ViewBag.CurrentPage + 1)"> <i class="w-4 h-4" data-feather="chevron-right"></i> </a>
            </li>
            <li>
                <a class="pagination__link" asp-area="admin" asp-controller="ServiceCategory" asp-action="index" asp-route-page="@ViewBag.PageCount"> <i class="w-4 h-4" data-feather="chevrons-right"></i> </a>
            </li>
        </ul>

    </div>
    <!-- END: Pagination -->
</div>
<!-- BEGIN: Delete Confirmation Modal -->
<div class="modal" id="delete-confirmation-modal">
    <div class="modal__content">
        <div class="p-5 text-center">
            <i data-feather="x-circle" class="w-16 h-16 text-theme-6 mx-auto mt-3"></i>
            <div class="text-3xl mt-5">Are you sure?</div>
            <div class="text-gray-600 mt-2">Do you really want to delete these records? This process cannot be undone.</div>
        </div>
        <div class="px-5 pb-8 text-center">
            <a asp-area="Admin" asp-controller="ServiceCategory" asp-action="index" data-dismiss="modal" class="button w-24 border text-gray-700 mr-1">Cancel</a>
            <button type="button" class="button w-24 bg-theme-6 text-white">Delete</button>
        </div>
    </div>
</div>

Trax/Trax/Areas/Admin/Views/ServiceCategory/Update.cshtml
@model ServiceCategory
@{
    ViewData["Title"] = "Update";
}

<div class="intro-y flex items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Update Position
    </h2>
</div>
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 lg:col-span-6">
        <!-- BEGIN: Form Layout -->
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" style="color:red; margin-bottom:30px;"></div>
            <div class="intro-y box p-5">
                <input asp-for="Id" hidden />
                <div>
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="input w-full border mt-2" placeholder="Input text">
                </div>

                <div class="text-right mt-5">
                    <a asp-area="admin" asp-controller="ServiceCategory" asp-action="index" class="button w-24 border text-gray-700 mr-1">Cancel</a>
                    <button type="submit" class="button w-24 bg-theme-1 text-white">Update</button>
                </div>
            </div>
        </form>
        <!-- END: Form Layout -->
    </div>
</div>